# Generated by Django 6.0 on 2026-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_name', models.CharField(max_length=100)),
                ('dat_created', models.DateTimeField()),
                ('dat_updated', models.DateTimeField()),
            ],
        ),
    ]
