# Generated by Django 6.0 on 2026-01-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dat_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='dat_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
