# Generated by Django 6.0 on 2026-01-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_dat_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='int_status',
            field=models.IntegerField(default=1),
        ),
    ]
