# Generated by Django 6.0 on 2026-01-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_int_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_name', models.CharField(max_length=200)),
                ('vchr_description', models.TextField(blank=True, null=True)),
                ('int_stock_qty', models.IntegerField(blank=True, null=True)),
                ('dbl_selling_price', models.FloatField(blank=True, null=True)),
                ('dbl_offer_price', models.FloatField(blank=True, null=True)),
                ('jsn_images', models.JSONField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_status', models.IntegerField(default=1)),
                ('fk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
