# Generated by Django 6.0 on 2026-01-13 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bint_phone', models.BigIntegerField(blank=True, null=True)),
                ('int_pincode', models.IntegerField(blank=True, null=True)),
                ('vchr_address', models.TextField(blank=True, null=True)),
                ('vchr_state', models.CharField(blank=True, max_length=200, null=True)),
                ('vchr_district', models.CharField(blank=True, max_length=200, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('dbl_total_amt', models.FloatField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('dbl_ppu', models.FloatField(blank=True, null=True)),
                ('dbl_total_amt', models.FloatField(blank=True, null=True)),
                ('fk_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.cart')),
                ('fk_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
            ],
            options={
                'db_table': 'cart_details',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_order', models.DateTimeField(blank=True, null=True)),
                ('int_fop', models.IntegerField(blank=True, null=True)),
                ('dbl_total_amt', models.FloatField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('fk_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.address')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('dbl_ppu', models.FloatField(blank=True, null=True)),
                ('dbl_total_amt', models.FloatField(blank=True, null=True)),
                ('fk_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
                ('fk_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
