
# Generated by Django 6.0 on 2026-08-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
