# Generated by Django 6.0 on 2026-08-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.BigIntegerField(default=0, editable=False, unique=True),
        ),
    ]
